### PR TITLE
Document and test meaning of VersionReq::default

### PR DESCRIPTION
**Pull request by jonhoo**
I had to go searching through the code to verify, so figured it'd be worthwhile to document explicitly.

### CODE REVIEW

**Review by dtolnay — COMMENTED** [review]
For your use case would it have been sufficient for the `Default` impl to be documented?

Screenshot from 2021-07-07 15-54-06

**Comment by jonhoo** [comment]
Honestly, I would probably have missed that. I rarely think to check documentation of implementation of standard traits, because it so rare that anyone overrides them, and they are collapsed in the default view. If rustdoc expanded documentation for standard traits _if_ they've been overridden, but barring that I think calling it out explicitly is worthwhile.

**Review by dtolnay — COMMENTED** [review]
Revisiting this, I think people popping open the source for the `impl Default` is going to be fine. I've found that more documentation just makes everyone read less of it so I've tried to be selective about what gets dedicated space in the documentation, and for something like this I think relatively few people will want to know, and those people can more easily find it out in the source than finding it in the documentation.

I pushed #267 so that the \[src\] link in the rustdoc takes you to an impl that looks like the following rather than just a derive:

```rust
impl Default for VersionReq {
    fn default() -> Self {
        VersionReq::STAR
    }
}
```

and I copied the test changes from this PR over to #269.

**Comment by jonhoo** [comment]
I like that as a solution, thanks!

**Pull request closed without merging**
